# Git aliases
alias g='git'
alias gs='git status'
alias gd='git --no-pager diff'
alias gds='git --no-pager diff --staged'
alias gdstat='git diff --stat'
alias glog='git log --oneline --graph --decorate'
alias gb='git branch'
alias gco='git checkout'
alias gc='git commit -v'
alias gpl='git pull'
alias gps='git push'
alias gf='git fetch'
alias gst='git stash'
alias gstp='git stash pop'
alias gcl='git clone'
alias gclean='git clean -fd'
